package it.unitn.hci.feed.models;

public enum Subject
{
    GENERIC, FORMAL_LANGUAGES_AND_COMPILERS, INTRODUCTION_TO_CELL_BIOLOGY, PERCORSO_DI_ECCELLENZA_1, ANALISI_MATEMATICA_III, INFORMATICA_ESERCITAZIONE, MACHINE_LEARNING,
}
